services:
  db:
    image: mysql:latest
    ports:
    - 3306:3306
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
    - ./db:/docker-entrypoint-initdb.d/
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
    - 5500:80
    #  environment:
    #    - PMA_HOST = db
    #    - PMA_USER = ${DATABASE_USER}
    #    - PMA_PASSWORD = ${DATABASE_PASSWORD}