version: "3.3"

services:
  db:
    container_name: db
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports: 
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 5500:80
    environment: 
      - PMA_HOST=db
      - PMA_USER=${DATABASE_USERNAME}
      - PMA_PASSWORD=${DATABASE_PASSWORD}